### PR TITLE
BOSA21Q1-789 Fix missing aria label on flag icon

### PR DESCRIPTION
**Pull request by ThomasCollignon**
[BOSA21Q1-789](https://belighted.atlassian.net/browse/BOSA21Q1-789)

There may be impacts on accessibility. I've tested with a screen reader, the label is read twice. Not sure I can do better.

### CODE REVIEW

**Review by simon-lejeune — APPROVED** [review]

**Comment by sergei-krylov** [comment]
@ThomasCollignon it read label twice because there is 2 labels available for screen reader, because you removed the `aria-hidden` attribute.

**Comment by sergei-krylov** [comment]
@ThomasCollignon , a point to double check - the ticket mention that it should be a `clear label, e.g. "Report a problem with this idea"`. So should it be a label instead of just flag icon?

**Comment by sergei-krylov** [comment]
Ok, let's keep it like this for now.
And regarding the second question - should it transform from icon to a label, or should it remain an icon with tooltip?

**Comment by ThomasCollignon** [comment]
> Ok, let's keep it like this for now. And regarding the second question - should it transform from icon to a label, or should it remain an icon with tooltip?

I'm waiting for their answer in the ticket.

**Review by sergei-krylov — APPROVED** [review]

**Pull request merged**
